### ISSUE TITLE
Better way of handling deprecated cl functions on older emacs

### ISSUE THREAD

**Issue by jorissteyn** [emacs-php/php-mode#245]
A bug in cc-mode [1] in emacs 24.4 required requiring 'cl. In the fix for issue [2] this workaround was applied to all future versions as well. This fixes issue #238, but is not ideal. The whole reason of deprecating those functions it that people start using the ones with cl- prefixes. So I think we should use cl-lib where possible, and not pull in the compatibility layer on newer emacses.

This needs some research and proper fixing.

[1] http://lists.gnu.org/archive/html/bug-gnu-emacs/2014-10/msg01175.html
[2] https://github.com/ejmr/php-mode/issues/238

**Comment by ejmr** [comment]
Thanks for bringing this up.  I'll try to look into it over the weekend, although admittedly I'm going to be pretty busy, so I don't know how much research I'll get done.  Any help from anyone else will be greatly appreciated as always.

**Comment by calbrecht** [comment]
Might this be a solution to require only when compiling? Like it is written in the [elisp manual Coding Conventions](https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Coding-Conventions)

'If you need Common Lisp extensions, use the cl-lib library rather than the old cl library. The latter does not use a clean namespace (i.e., its definitions do not start with a ‘cl-’ prefix). If your package loads cl at run time, that could cause name clashes for users who don't use that package.

There is no problem with using the cl package at compile time, with (eval-when-compile (require 'cl)). That's sufficient for using the macros in the cl package, because the compiler expands them before generating the byte-code. It is still better to use the more modern cl-lib in this case, though. '
