### ISSUE TITLE
emacs25 - indentation & syntax highlighting broken

### ISSUE THREAD

**Issue by eoghanmurray** [emacs-php/php-mode#371]
Upon upgrade to emacs25 and installing latest version of php-mode 1.18.3 I've noticed the mode produces incorrect syntax highlighting (and hence incorrectly indents etc.) after code editing of a large file.  After I make some edit that messes up syntax highlighting, I have to manually call `php-mode` to fix syntax highlighting (this takes a number of seconds to execute) only to have the mode break again moments later after my next edit.  I've done a git bisect and have traced this breakage back to https://github.com/ejmr/php-mode/commit/86eab8013c566eebcb77dadf5616b3e99e0eeb1d
I've disabled that call to `php-syntax-propertize-function` in my local version of php-mode and will report back if that has fixed it for good.

I've got one largish file that reliably triggers the breakage upon editing, it's very hard to pin down exactly what combination of code is causing the breakage, but let me know if you can't recreate and I'll try to cobble together some sort of a minimal test case.

**Comment by ejmr** [comment]
Thank you for the bug report and the `git-bisect` information.  Is it possible for you to post that file which triggers the error?  It would be useful for correcting and testing both this issue and #370, since I will not be surprised if the bugs are related in some way.

If you cannot or do not want to post that file publically then you can, if you wish, e-mail it to me privately at `ericjmritz@yandex.com`.  And if you cannot share it privately---e.g. legal reasons if it is source code from a professional product---then that is ok too, as I understand that's not always possible to do.  Regardless, thank you again for the information and help you've already provided.

**Comment by ejmr** [comment]
I apologize for the delay [but unexpected things have kept me from doing much](https://www.reddit.com/r/emacs/comments/72k9tf/php_mode_to_change_ownership_in_one_month/).  Regarding that file you sent me: I will *not* give it to anyone else, including anyone who takes over PHP Mode.  You have my word that no one besides me will ever see it.

**Comment by fallchildren** [comment]
Is this still a problem with current php-mode master?
