### ISSUE TITLE
Status of 1.20.0 release

### ISSUE THREAD

**Issue by ryandesign** [emacs-php/php-mode#494]
The 1.20.0 tag was created a month ago, but there is no corresponding GitHub release object with release notes, and 1.19.1 is still marked as the [latest release](
https://github.com/emacs-php/php-mode/releases/latest). Should 1.20.0 be used or no? If so, can it be promoted to the latest release?

**Comment by zonuexe** [comment]
@ryandesign 
Thank you for your suggestion and I am sorry for confusing you because my work was inadequate.
The package that can be obtained from [MELPA stable: php-mode](https://stable.melpa.org/#/php-mode) is always stable version.

[![MELPA Stable](https://stable.melpa.org/packages/php-mode-badge.svg)](https://stable.melpa.org/#/php-mode)

**Comment by ryandesign** [comment]
Thanks!

**Comment by zonuexe** [comment]
@ryandesign I appreciate that you took care of our Changelog.
