### ISSUE TITLE
Integrate php-cs-fixer

### ISSUE THREAD

**Issue by someonewithpc** [emacs-php/php-mode#616]
I think it would be beneficial to include https://github.com/OVYA/php-cs-fixer with php-mode. I, however, have my own fork, which I believe works better and in a more straightforward way, at https://github.com/someonewithpc/php-cs-fixer

I opened a pull request in the original project, but it was rejected as "too extreme", which is fair, but their version did not work for me.

I'm open to make a pull request, but I'd like comments on which version is considered more appropriate.

**Comment by zonuexe** [comment]
@someonewithpc 
`php-format.el` was merged by https://github.com/emacs-php/php-mode/pull/731. `php-format-auto-mode` probably covers your use case. Not well documented yet, but should work easily if your project has `.php-cs-fixer.dist.php` or `php-cs-fixer.php` file.

Please give me feedback if you have any thoughts on the user experience of this mode. thank you!

**Comment by NateEag** [comment]
[apheleia-mode](https://github.com/radian-software/apheleia) is a general package for using code formatters asynchronously, which people viewing this issue may be interested in.

I'm not currently writing PHP, but next time I am, I'll probably be tweaking my configuration to apply PHP code formatters via `apheleia-mode`.

**Comment by zonuexe** [comment]
@NateEag
Thanks for suggesting!

PHP formatters tend to rewrite files directly instead of supporting stdin. I also implemented it by applying the RCS patch at first, but I was able to edit it more smoothly by starting the process asynchronously from the timer.

Since the way the autoformat results are reflected in the Emacs buffer is a matter of user choice and preference, we will also document other options.
