### ISSUE TITLE
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c++-

### ISSUE THREAD

**Issue by wpasieka** [emacs-php/php-mode#648]
The emacs-snapshot is installed, never had anything like that, I understand what is says, but in the packages-list-packages the cc-mode built-in version is shown as 5.33, so 5.34 can't be loaded:

Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c++-template-syntax-table’ (fallback source eval - php-mode compiled with CC Mode 5.33 but loaded with
5.34.2): (error "‘c++-make-template-syntax-table’ got no (prior) value in php-mode (might be a cyclic reference)")

How to solve it, please?

**Comment by zonuexe** [comment]
@wpasieka 
Maybe, same as #562 and #617. Please try reinstall or rebuild (byte-compile) PHP Mode.

**Comment by wpasieka** [comment]
Thank You for the advice, but an overall problem is different.

I have removed a php-mode, in package-list-packages, but the php-mode was still working.
It means it is compiled somewhere by another program, which is using it.

But finding which this very program is almost mission impossible.
Grepping elpa packages showed php-mode in many scripts.

It is confirmed by some information on the internet, where people where removing emacs.
Emacs was reinstalled, but the error stayed.

I have "solved" the problem by returning from emacs-snapshot to the emacs26.

A suggestion for php-mode developers is to keep the NEWEST version of the CC-mode in Elpa.
It currently shows it as 5.33, built-in, so  nothing can be done by the emacs users.
Having the newest version built-in would allow to use byte-recompiled directory.
And we don't need to know where the php-mode is used.

**Comment by zonuexe** [comment]
@wpasieka 
Try removing it directly from the filesystem instead of from `list-packages`, restarting Emacs and then installing php-mode.
For example `rm -rf ~/.emacs.d/elpa/php-mode-*`

> A suggestion for php-mode developers is to keep the NEWEST version of the CC-mode in Elpa.

I don't understand the meaning of the suggestion, how can we do it?

**Comment by NateEag** [comment]
@zonuexe I believe the idea is to declare a dependency on a specific version of `cc-mode.el` in ELPA or MELPA.

`package.el` would then ensure the required version is always on disk in the configured `elpa/` directory, and thus available for byte-compilation that's compatible with the installed `php-mode.el`.

However, cc-mode is not available as a package [in MELPA](https://melpa.org/#/?q=cc-mode) or [in GNU ELPA (search for `cc-mode`)](https://elpa.gnu.org/packages/).

That's because [cc-mode is maintained and shipped as part of Emacs](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/cc-mode.el).

As far as I can tell, [the Emacs maintainers want to get it into ELPA](https://www.reddit.com/r/emacs/comments/564ns0/why_ccmode_is_released_with_emacs_why_not_melpa/d8gqwb8/), but no one has achieved it yet - [this thread with an attempt to do it devolved into bikeshedding](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/cc-mode.el).

I doubt the MELPA maintainers would accept a recipe for cc-mode.el, as it is a part of core Emacs and an installable package belongs on ELPA, not MELPA.

@wpasieka If you want to take that approach for now, I'd recommend installing `cc-mode.el` into your .emacs.d manually, then making sure `load-path` is configured so your installed version is found first. I think that might solve your problem.

**Comment by zonuexe** [comment]
Hmm, I understand @wpasieka's suggestion, but PHP Mode depends on macros provided by CC Mode, so the best solution is to recompile PHP Mode.

The only thing we can do is detect CC Mode updates and prompt the user to run `M-x package-reinstall php-mode`. I will prepare this patch.

**Comment by wpasieka** [comment]
@zonuexe said:  “The only thing we can do is detect CC Mode updates and prompt the user to run M-x package-reinstall php-mode. I will prepare this patch.  I will prepare this patch.”

It is an important step forward, and it will also make life of the php-mode developers much easier.
With the package and its ALL dependencies up-to-date, no error shall happen at emacs upgrade.
This shall become the norm for all emacs packages.
