### ISSUE TITLE
Question about relation with lsp-modes

### ISSUE THREAD

**Issue by rdbeni0** [emacs-php/php-mode#794]
Hello,

What is the relationship between this package and lsp-mode (for example: eglot + phpactor)? 
Do both packages provide "auto-completion" at the same time?
Can these packages be used simultaneously? 
I'm wondering if there will be any overlap and duplication of functionality.

Sorry for this question, but its not really clear for me.
Thanks!

**Comment by NateEag** [comment]
`php-mode` is an Emacs [major mode](https://www.gnu.org/s/emacs/manual/html_node/emacs/Major-Modes.html). As such, it handles syntax coloration, indentation / formatting behavior, and other details of Emacs integration.

If you want language intelligence, such as "jump to definition", "find references", and "show docs on hover", that's what [a language server](https://microsoft.github.io/language-server-protocol/implementors/servers/) and [an LSP client](https://microsoft.github.io/language-server-protocol/implementors/tools/) are for.

It's been several years since I last wrote PHP, so my knowledge is slightly out-of-date, but I used `php-mode`, `lsp-mode`, and `php-language-server` together happily.

Looks like these days `phpactor` and `intelephense` are popular.

Check out the options from the links above and see which ones appeal to you.

I hope that helps!

**Comment by rdbeni0** [comment]
Ah, yes, you're right.

I know what I missed. I have ac-php ( https://github.com/xcwen/ac-php ) in my config as company-php, which is providing the code completions. 
I forgot, however, that it's a separate package from php-mode. And php-mode itself can be connected to lsp (but then I should disable ac-php company). Now everything is clear.

Sorry for the confusion.

**Comment by NateEag** [comment]
No worries, glad to be of assistance!
